services:
  postgres:
    image: postgres:16-alpine
    container_name: projeto-tarefas-db
    environment:
      POSTGRES_DB: projeto_tarefas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dados-postgres:/var/lib/postgresql/data
      - ./database/script_banco.sql:/docker-entrypoint-initdb.d/01-script_banco.sql:ro

volumes:
  dados-postgres:
